<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.internet.defer.Deferred.errback : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>

    <span style="display: none" id="current-docs-container">
      <em>
        <a id="current-docs-link">
          Go to the latest version of this document.
        </a>
      </em>
    </span>

    <h1 class="method">t.i.d.D.errback(self, fail=None) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.internet.html">internet</a>.<a href="twisted.internet.defer.html">defer</a>.<a href="twisted.internet.defer.Deferred.html">Deferred</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-10.2.0/twisted/internet/defer.py#L364">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div><p>Run all error callbacks that have been added to this <a 
href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a>.</p>
<p>Each callback will have its result passed as the first argument to the 
next; this way, the callbacks act as a 'processing chain'. Also, if the 
error-callback returns a non-Failure or doesn't raise an 
<code>Exception</code>, processing will continue on the *success*-callback 
chain.</p>
<p>If the argument that's passed to me is not a <a 
href="twisted.python.failure.Failure.html"><code>failure.Failure</code></a>
instance, it will be embedded in one. If no argument is passed, a <a 
href="twisted.python.failure.Failure.html"><code>failure.Failure</code></a>
instance will be created based on the current traceback stack.</p>
Passing a string as `fail' is deprecated, and will be punished with a 
warning message.
<table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Raises</td><td class="fieldArg">NoCurrentExceptionError</td><td>If <code>fail</code> is <code>None</code> but there is no current 
exception state.
</td></tr></table></div>

    
    
    <div id="splitTables">
      
      
      
    </div>
    
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a> at 2011-10-27 16:22:34.
    </address>

    <!-- Google analytics, obviously. -->
    <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
    <script type="text/javascript">
      _uacct = "UA-99018-6";
      urchinTracker();
    </script>

    <!-- If the documentation isn't current, insert a current link. -->
    <script type="text/javascript">
      if (window.location.pathname.indexOf('/current/') == -1) {
          <!-- Give the user a link to this page, but in the current version of the docs. -->
          var link = document.getElementById('current-docs-link');
          link.href = window.location.pathname.replace(/\/\d+\.\d+\.\d+\/api\//, '/current/api/');
          <!-- And make it visible -->
          var container = document.getElementById('current-docs-container');
          container.style.display = "";
          delete link;
          delete container;
      }
    </script>

  </body>
</html>